apiVersion: apps/v1
kind: Deployment
metadata:
  name: balanced-scheduler-normal
  labels:
    app: balanced-scheduler-normal
spec:
  replicas: 6
  selector:
    matchLabels:
      app: balanced-scheduler-normal
  template:
    metadata:
      labels:
        app: balanced-scheduler-normal
    spec:
      schedulerName: balanced-scheduler
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
